name: 功能建议
description: 提出一个新功能
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: 功能描述
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: 使用场景
      description: 为什么需要这个功能？
